--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-25-2023   
--------------------------------------------------------
DROP TABLE CALL;
DROP TABLE COMMON1;
DROP TABLE COMMON2;
DROP TABLE CSBOARD;
DROP TABLE CSBOARD_COMMENT;
DROP TABLE DDAY;
DROP TABLE EPHONE;
DROP TABLE FAVOR;
DROP TABLE FAV_BOARD;
DROP TABLE FAV_BOARD_COMMENT;
DROP TABLE FAV_BOARD_LIKE;
DROP TABLE GAME;
DROP TABLE LOCATION;
DROP TABLE MANNER;
DROP TABLE MEMBER;
DROP TABLE OPTION_TABLE;
DROP TABLE REGION;
DROP TABLE SENIOR;
DROP TABLE SENIOR_LIKE;
DROP TABLE MEMBER;
DROP TABLE COMMON1;
DROP TABLE CSBOARD;
DROP TABLE FAV_BOARD;
DROP TABLE SENIOR;
DROP TABLE CALL;
DROP TABLE COMMON2;
DROP TABLE CSBOARD_COMMENT;
DROP TABLE DDAY;
DROP TABLE EPHONE;
DROP TABLE FAVOR;
DROP TABLE FAV_BOARD_COMMENT;
DROP TABLE FAV_BOARD_LIKE;
DROP TABLE GAME;
DROP TABLE LOCATION;
DROP TABLE MANNER;
DROP TABLE OPTION_TABLE;
DROP TABLE REGION;
DROP TABLE SENIOR_LIKE;
--------------------------------------------------------
--  DDL for Table CALL
--------------------------------------------------------

  CREATE TABLE CALL 
   (	MEMBER_ID NVARCHAR2(15), 
	CALL_TIME DATE, 
	CALL_OPPONENET_ID NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table COMMON1
--------------------------------------------------------

  CREATE TABLE COMMON1 
   (	KEY1 NUMBER, 
	NAME NVARCHAR2(10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table COMMON2
--------------------------------------------------------

  CREATE TABLE COMMON2 
   (	KEY1 NUMBER, 
	KEY2 NUMBER, 
	NAME NVARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table CSBOARD
--------------------------------------------------------

  CREATE TABLE CSBOARD 
   (	CSBOARD_ID NUMBER, 
	WRITER NVARCHAR2(15), 
	CSBOARD_TITLE NVARCHAR2(50), 
	CSOBOARD_CONTENT NVARCHAR2(2000), 
	CSBOARD_VIEWCOUNT NUMBER, 
	CSBOARD_WRITEDATE DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table CSBOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE CSBOARD_COMMENT 
   (	CSBOARD_COMMENT_ID NUMBER, 
	CSBOARD_ID NUMBER, 
	WRITER NVARCHAR2(15), 
	CSBOARD_COMMENT_WRITER NVARCHAR2(15), 
	CSBOARD_COMMENT_CONTENT NVARCHAR2(1000), 
	CSBOARD_COMMENT_WRITEDATE DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table DDAY
--------------------------------------------------------

  CREATE TABLE DDAY 
   (	MEMBER_ID NVARCHAR2(15), 
	DDAY_DATE DATE, 
	DDAY_CONTENT NVARCHAR2(300)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table EPHONE
--------------------------------------------------------

  CREATE TABLE EPHONE 
   (	MEMBER_ID NVARCHAR2(15), 
	EPHONE_NAME NVARCHAR2(15), 
	EPHONE_PHONE NVARCHAR2(15), 
	EPHONE_RELATION NVARCHAR2(30), 
	EPHONE_PHONE_ID NVARCHAR2(300)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table FAVOR
--------------------------------------------------------

  CREATE TABLE FAVOR 
   (	FAVOR NUMBER, 
	MEMBER_ID NVARCHAR2(15)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table FAV_BOARD
--------------------------------------------------------

  CREATE TABLE FAV_BOARD 
   (	FAV_BOARD_ID NUMBER, 
	WRITER NVARCHAR2(15), 
	FAVOR NUMBER, 
	FAV_BOARD_TITLE NVARCHAR2(50), 
	FAV_BOARD_CONTENT NVARCHAR2(2000), 
	FAV_BOARD_WRITEDATE DATE DEFAULT sysdate, 
	FAV_BOARD_WRITECOUNT NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table FAV_BOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE FAV_BOARD_COMMENT 
   (	FAV_BOARD_COMMENT_ID NUMBER, 
	FAV_BOARD_ID NUMBER, 
	WRITER NVARCHAR2(15), 
	FAV_BOARD_COMMENT_CONTENT NVARCHAR2(1000), 
	FAV_BOARD_COMMENT_WRITEDATE DATE DEFAULT sysdate, 
	FAV_BOARD_COMMENT_WRITER NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table FAV_BOARD_LIKE
--------------------------------------------------------

  CREATE TABLE FAV_BOARD_LIKE 
   (	MEMBER_ID_LIKE NVARCHAR2(15), 
	FAV_BOARD_ID NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table GAME
--------------------------------------------------------

  CREATE TABLE GAME 
   (	GAME_RANK NUMBER, 
	MEMBER_ID NVARCHAR2(15), 
	GAME_SCORE NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE LOCATION 
   (	MEMBER_ID NVARCHAR2(15), 
	LOCATION_LATITUDE NVARCHAR2(30), 
	LOCATION_LONGITUDE NVARCHAR2(30), 
	LOCATION_TIME DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table MANNER
--------------------------------------------------------

  CREATE TABLE MANNER 
   (	MANNER_OPPONENT_ID NVARCHAR2(15), 
	MEMBER_ID NVARCHAR2(15), 
	MANNER_SCORE NUMBER DEFAULT 50
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE MEMBER 
   (	MEMBER_ID NVARCHAR2(15), 
	MEMBER_PW NVARCHAR2(18), 
	MEMBER_NAME NVARCHAR2(30), 
	MEMBER_NICKNAME NVARCHAR2(30), 
	MEMBER_AGE NUMBER, 
	MEMBER_GENDER NVARCHAR2(1), 
	MEMBER_PHONE NVARCHAR2(15), 
	MEMBER_PROFILEIMG NVARCHAR2(2000), 
	MEMBER_PHONE_ID NVARCHAR2(300), 
	MEMBER_MANNER_SCORE NUMBER DEFAULT 50, 
	MEMBER_ADMIN NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table OPTION_TABLE
--------------------------------------------------------

  CREATE TABLE OPTION_TABLE 
   (	MEMBER_ID NVARCHAR2(15), 
	OPTION_FONT_SIZE NUMBER DEFAULT 20, 
	OPTION_FONT_COLOR NVARCHAR2(30) DEFAULT '#000000', 
	OPTION_ALARM NVARCHAR2(3) DEFAULT 'N', 
	OPTION_LOCK_PW NUMBER, 
	OPTION_GODOK_ALARM NVARCHAR2(3) DEFAULT 'N'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table REGION
--------------------------------------------------------

  CREATE TABLE REGION 
   (	REGION NVARCHAR2(20), 
	MEMBER_ID NVARCHAR2(15), 
	ADDRESS NVARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table SENIOR
--------------------------------------------------------

  CREATE TABLE SENIOR 
   (	KEY NUMBER, 
	SENIOR_NAME NVARCHAR2(30), 
	SENIOR_ROADADDRESS NVARCHAR2(200), 
	SENIOR_NUMADDRESS NVARCHAR2(200), 
	SENIOR_CALL NVARCHAR2(20), 
	SENIOR_LATITUDE NVARCHAR2(30), 
	SENIOR_LONGITUDE NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table SENIOR_LIKE
--------------------------------------------------------

  CREATE TABLE SENIOR_LIKE 
   (	MEMBER_ID NVARCHAR2(15), 
	KEY NUMBER, 
	SENIOR_LIKE_NUM NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE MEMBER 
   (	MEMBER_ID NVARCHAR2(15), 
	MEMBER_PW NVARCHAR2(18), 
	MEMBER_NAME NVARCHAR2(30), 
	MEMBER_NICKNAME NVARCHAR2(30), 
	MEMBER_AGE NUMBER, 
	MEMBER_GENDER NVARCHAR2(1), 
	MEMBER_PHONE NVARCHAR2(15), 
	MEMBER_PROFILEIMG NVARCHAR2(2000), 
	MEMBER_PHONE_ID NVARCHAR2(300), 
	MEMBER_MANNER_SCORE NUMBER DEFAULT 50, 
	MEMBER_ADMIN NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table COMMON1
--------------------------------------------------------

  CREATE TABLE COMMON1 
   (	KEY1 NUMBER, 
	NAME NVARCHAR2(10)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table CSBOARD
--------------------------------------------------------

  CREATE TABLE CSBOARD 
   (	CSBOARD_ID NUMBER, 
	WRITER NVARCHAR2(15), 
	CSBOARD_TITLE NVARCHAR2(50), 
	CSOBOARD_CONTENT NVARCHAR2(2000), 
	CSBOARD_VIEWCOUNT NUMBER, 
	CSBOARD_WRITEDATE DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table FAV_BOARD
--------------------------------------------------------

  CREATE TABLE FAV_BOARD 
   (	FAV_BOARD_ID NUMBER, 
	WRITER NVARCHAR2(15), 
	FAVOR NUMBER, 
	FAV_BOARD_TITLE NVARCHAR2(50), 
	FAV_BOARD_CONTENT NVARCHAR2(2000), 
	FAV_BOARD_WRITEDATE DATE DEFAULT sysdate, 
	FAV_BOARD_WRITECOUNT NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table SENIOR
--------------------------------------------------------

  CREATE TABLE SENIOR 
   (	KEY NUMBER, 
	SENIOR_NAME NVARCHAR2(30), 
	SENIOR_ROADADDRESS NVARCHAR2(200), 
	SENIOR_NUMADDRESS NVARCHAR2(200), 
	SENIOR_CALL NVARCHAR2(20), 
	SENIOR_LATITUDE NVARCHAR2(30), 
	SENIOR_LONGITUDE NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table CALL
--------------------------------------------------------

  CREATE TABLE CALL 
   (	MEMBER_ID NVARCHAR2(15), 
	CALL_TIME DATE, 
	CALL_OPPONENET_ID NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table COMMON2
--------------------------------------------------------

  CREATE TABLE COMMON2 
   (	KEY1 NUMBER, 
	KEY2 NUMBER, 
	NAME NVARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table CSBOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE CSBOARD_COMMENT 
   (	CSBOARD_COMMENT_ID NUMBER, 
	CSBOARD_ID NUMBER, 
	WRITER NVARCHAR2(15), 
	CSBOARD_COMMENT_WRITER NVARCHAR2(15), 
	CSBOARD_COMMENT_CONTENT NVARCHAR2(1000), 
	CSBOARD_COMMENT_WRITEDATE DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table DDAY
--------------------------------------------------------

  CREATE TABLE DDAY 
   (	MEMBER_ID NVARCHAR2(15), 
	DDAY_DATE DATE, 
	DDAY_CONTENT NVARCHAR2(300)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table EPHONE
--------------------------------------------------------

  CREATE TABLE EPHONE 
   (	MEMBER_ID NVARCHAR2(15), 
	EPHONE_NAME NVARCHAR2(15), 
	EPHONE_PHONE NVARCHAR2(15), 
	EPHONE_RELATION NVARCHAR2(30), 
	EPHONE_PHONE_ID NVARCHAR2(300)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table FAVOR
--------------------------------------------------------

  CREATE TABLE FAVOR 
   (	FAVOR NUMBER, 
	MEMBER_ID NVARCHAR2(15)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table FAV_BOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE FAV_BOARD_COMMENT 
   (	FAV_BOARD_COMMENT_ID NUMBER, 
	FAV_BOARD_ID NUMBER, 
	WRITER NVARCHAR2(15), 
	FAV_BOARD_COMMENT_CONTENT NVARCHAR2(1000), 
	FAV_BOARD_COMMENT_WRITEDATE DATE DEFAULT sysdate, 
	FAV_BOARD_COMMENT_WRITER NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table FAV_BOARD_LIKE
--------------------------------------------------------

  CREATE TABLE FAV_BOARD_LIKE 
   (	MEMBER_ID_LIKE NVARCHAR2(15), 
	FAV_BOARD_ID NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table GAME
--------------------------------------------------------

  CREATE TABLE GAME 
   (	GAME_RANK NUMBER, 
	MEMBER_ID NVARCHAR2(15), 
	GAME_SCORE NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE LOCATION 
   (	MEMBER_ID NVARCHAR2(15), 
	LOCATION_LATITUDE NVARCHAR2(30), 
	LOCATION_LONGITUDE NVARCHAR2(30), 
	LOCATION_TIME DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table MANNER
--------------------------------------------------------

  CREATE TABLE MANNER 
   (	MANNER_OPPONENT_ID NVARCHAR2(15), 
	MEMBER_ID NVARCHAR2(15), 
	MANNER_SCORE NUMBER DEFAULT 50
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table OPTION_TABLE
--------------------------------------------------------

  CREATE TABLE OPTION_TABLE 
   (	MEMBER_ID NVARCHAR2(15), 
	OPTION_FONT_SIZE NUMBER DEFAULT 20, 
	OPTION_FONT_COLOR NVARCHAR2(30) DEFAULT '#000000', 
	OPTION_ALARM NVARCHAR2(3) DEFAULT 'N', 
	OPTION_LOCK_PW NUMBER, 
	OPTION_GODOK_ALARM NVARCHAR2(3) DEFAULT 'N'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table REGION
--------------------------------------------------------

  CREATE TABLE REGION 
   (	REGION NVARCHAR2(20), 
	MEMBER_ID NVARCHAR2(15), 
	ADDRESS NVARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Table SENIOR_LIKE
--------------------------------------------------------

  CREATE TABLE SENIOR_LIKE 
   (	MEMBER_ID NVARCHAR2(15), 
	KEY NUMBER, 
	SENIOR_LIKE_NUM NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS ;
REM INSERTING into AA.CALL
SET DEFINE OFF;
REM INSERTING into AA.COMMON1
SET DEFINE OFF;
REM INSERTING into AA.COMMON2
SET DEFINE OFF;
REM INSERTING into AA.CSBOARD
SET DEFINE OFF;
REM INSERTING into AA.CSBOARD_COMMENT
SET DEFINE OFF;
REM INSERTING into AA.DDAY
SET DEFINE OFF;
REM INSERTING into AA.EPHONE
SET DEFINE OFF;
REM INSERTING into AA.FAVOR
SET DEFINE OFF;
REM INSERTING into AA.FAV_BOARD
SET DEFINE OFF;
REM INSERTING into AA.FAV_BOARD_COMMENT
SET DEFINE OFF;
REM INSERTING into AA.FAV_BOARD_LIKE
SET DEFINE OFF;
REM INSERTING into AA.GAME
SET DEFINE OFF;
REM INSERTING into AA.LOCATION
SET DEFINE OFF;
REM INSERTING into AA.MANNER
SET DEFINE OFF;
REM INSERTING into AA.MEMBER
SET DEFINE OFF;
REM INSERTING into AA.OPTION_TABLE
SET DEFINE OFF;
REM INSERTING into AA.REGION
SET DEFINE OFF;
REM INSERTING into AA.SENIOR
SET DEFINE OFF;
REM INSERTING into AA.SENIOR_LIKE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_CALL
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CALL ON CALL (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_COMMON1
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_COMMON1 ON COMMON1 (KEY1) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_COMMON2
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_COMMON2 ON COMMON2 (KEY1) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_CSBOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CSBOARD ON CSBOARD (CSBOARD_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_CSBOARD_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CSBOARD_COMMENT ON CSBOARD_COMMENT (CSBOARD_COMMENT_ID, CSBOARD_ID, WRITER) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_DDAY
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_DDAY ON DDAY (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_EPHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_EPHONE ON EPHONE (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_FAVOR
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_FAVOR ON FAVOR (FAVOR, MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_FAV_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_FAV_BOARD ON FAV_BOARD (FAV_BOARD_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_FAV_BOARD_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_FAV_BOARD_COMMENT ON FAV_BOARD_COMMENT (FAV_BOARD_COMMENT_ID, WRITER, FAV_BOARD_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_FAV_BOARD_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_FAV_BOARD_LIKE ON FAV_BOARD_LIKE (MEMBER_ID_LIKE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_GAME
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_GAME ON GAME (GAME_RANK, MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_LOCATION
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_LOCATION ON LOCATION (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_MANNER
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_MANNER ON MANNER (MANNER_OPPONENT_ID, MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_MEMBER ON MEMBER (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_OPTION_TABLE
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_OPTION_TABLE ON OPTION_TABLE (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_REGION
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_REGION ON REGION (REGION, MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_SENIOR
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_SENIOR ON SENIOR (KEY) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_SENIOR_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_SENIOR_LIKE ON SENIOR_LIKE (MEMBER_ID, KEY) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_CALL
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CALL ON CALL (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_COMMON1
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_COMMON1 ON COMMON1 (KEY1) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_COMMON2
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_COMMON2 ON COMMON2 (KEY1) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_CSBOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CSBOARD ON CSBOARD (CSBOARD_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_CSBOARD_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CSBOARD_COMMENT ON CSBOARD_COMMENT (CSBOARD_COMMENT_ID, CSBOARD_ID, WRITER) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_DDAY
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_DDAY ON DDAY (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_EPHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_EPHONE ON EPHONE (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_FAVOR
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_FAVOR ON FAVOR (FAVOR, MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_FAV_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_FAV_BOARD ON FAV_BOARD (FAV_BOARD_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_FAV_BOARD_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_FAV_BOARD_COMMENT ON FAV_BOARD_COMMENT (FAV_BOARD_COMMENT_ID, WRITER, FAV_BOARD_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_FAV_BOARD_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_FAV_BOARD_LIKE ON FAV_BOARD_LIKE (MEMBER_ID_LIKE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_GAME
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_GAME ON GAME (GAME_RANK, MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_LOCATION
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_LOCATION ON LOCATION (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_MANNER
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_MANNER ON MANNER (MANNER_OPPONENT_ID, MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_MEMBER ON MEMBER (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_OPTION_TABLE
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_OPTION_TABLE ON OPTION_TABLE (MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_REGION
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_REGION ON REGION (REGION, MEMBER_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_SENIOR
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_SENIOR ON SENIOR (KEY) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  DDL for Index PK_SENIOR_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_SENIOR_LIKE ON SENIOR_LIKE (MEMBER_ID, KEY) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS ;
--------------------------------------------------------
--  Constraints for Table CALL
--------------------------------------------------------

  ALTER TABLE CALL MODIFY (MEMBER_ID NOT NULL ENABLE);
  ALTER TABLE CALL MODIFY (CALL_TIME NOT NULL ENABLE);
  ALTER TABLE CALL MODIFY (CALL_OPPONENET_ID NOT NULL ENABLE);
  ALTER TABLE CALL ADD CONSTRAINT PK_CALL PRIMARY KEY (MEMBER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMON1
--------------------------------------------------------

  ALTER TABLE COMMON1 MODIFY (KEY1 NOT NULL ENABLE);
  ALTER TABLE COMMON1 MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE COMMON1 ADD CONSTRAINT PK_COMMON1 PRIMARY KEY (KEY1)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMON2
--------------------------------------------------------

  ALTER TABLE COMMON2 MODIFY (KEY1 NOT NULL ENABLE);
  ALTER TABLE COMMON2 MODIFY (KEY2 NOT NULL ENABLE);
  ALTER TABLE COMMON2 MODIFY (NAME NOT NULL ENABLE);
  ALTER TABLE COMMON2 ADD CONSTRAINT PK_COMMON2 PRIMARY KEY (KEY1)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table CSBOARD
--------------------------------------------------------

  ALTER TABLE CSBOARD MODIFY (CSBOARD_ID NOT NULL ENABLE);
  ALTER TABLE CSBOARD MODIFY (WRITER NOT NULL ENABLE);
  ALTER TABLE CSBOARD MODIFY (CSBOARD_TITLE NOT NULL ENABLE);
  ALTER TABLE CSBOARD MODIFY (CSOBOARD_CONTENT NOT NULL ENABLE);
  ALTER TABLE CSBOARD MODIFY (CSBOARD_VIEWCOUNT NOT NULL ENABLE);
  ALTER TABLE CSBOARD MODIFY (CSBOARD_WRITEDATE NOT NULL ENABLE);
  ALTER TABLE CSBOARD ADD CONSTRAINT PK_CSBOARD PRIMARY KEY (CSBOARD_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table CSBOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE CSBOARD_COMMENT MODIFY (CSBOARD_COMMENT_ID NOT NULL ENABLE);
  ALTER TABLE CSBOARD_COMMENT MODIFY (CSBOARD_ID NOT NULL ENABLE);
  ALTER TABLE CSBOARD_COMMENT MODIFY (WRITER NOT NULL ENABLE);
  ALTER TABLE CSBOARD_COMMENT MODIFY (CSBOARD_COMMENT_WRITER NOT NULL ENABLE);
  ALTER TABLE CSBOARD_COMMENT MODIFY (CSBOARD_COMMENT_CONTENT NOT NULL ENABLE);
  ALTER TABLE CSBOARD_COMMENT MODIFY (CSBOARD_COMMENT_WRITEDATE NOT NULL ENABLE);
  ALTER TABLE CSBOARD_COMMENT ADD CONSTRAINT PK_CSBOARD_COMMENT PRIMARY KEY (CSBOARD_COMMENT_ID, CSBOARD_ID, WRITER)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table DDAY
--------------------------------------------------------

  ALTER TABLE DDAY MODIFY (MEMBER_ID NOT NULL ENABLE);
  ALTER TABLE DDAY MODIFY (DDAY_DATE NOT NULL ENABLE);
  ALTER TABLE DDAY MODIFY (DDAY_CONTENT NOT NULL ENABLE);
  ALTER TABLE DDAY ADD CONSTRAINT PK_DDAY PRIMARY KEY (MEMBER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table EPHONE
--------------------------------------------------------

  ALTER TABLE EPHONE MODIFY (MEMBER_ID NOT NULL ENABLE);
  ALTER TABLE EPHONE MODIFY (EPHONE_NAME NOT NULL ENABLE);
  ALTER TABLE EPHONE MODIFY (EPHONE_PHONE NOT NULL ENABLE);
  ALTER TABLE EPHONE ADD CONSTRAINT PK_EPHONE PRIMARY KEY (MEMBER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAVOR
--------------------------------------------------------

  ALTER TABLE FAVOR MODIFY (FAVOR NOT NULL ENABLE);
  ALTER TABLE FAVOR MODIFY (MEMBER_ID NOT NULL ENABLE);
  ALTER TABLE FAVOR ADD CONSTRAINT PK_FAVOR PRIMARY KEY (FAVOR, MEMBER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAV_BOARD
--------------------------------------------------------

  ALTER TABLE FAV_BOARD MODIFY (FAV_BOARD_ID NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD MODIFY (WRITER NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD MODIFY (FAVOR NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD MODIFY (FAV_BOARD_TITLE NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD MODIFY (FAV_BOARD_CONTENT NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD MODIFY (FAV_BOARD_WRITEDATE NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD MODIFY (FAV_BOARD_WRITECOUNT NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD ADD CONSTRAINT PK_FAV_BOARD PRIMARY KEY (FAV_BOARD_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAV_BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE FAV_BOARD_COMMENT MODIFY (FAV_BOARD_COMMENT_ID NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD_COMMENT MODIFY (FAV_BOARD_ID NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD_COMMENT MODIFY (WRITER NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD_COMMENT MODIFY (FAV_BOARD_COMMENT_CONTENT NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD_COMMENT MODIFY (FAV_BOARD_COMMENT_WRITEDATE NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD_COMMENT MODIFY (FAV_BOARD_COMMENT_WRITER NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD_COMMENT ADD CONSTRAINT PK_FAV_BOARD_COMMENT PRIMARY KEY (FAV_BOARD_COMMENT_ID, WRITER, FAV_BOARD_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAV_BOARD_LIKE
--------------------------------------------------------

  ALTER TABLE FAV_BOARD_LIKE MODIFY (MEMBER_ID_LIKE NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD_LIKE MODIFY (FAV_BOARD_ID NOT NULL ENABLE);
  ALTER TABLE FAV_BOARD_LIKE ADD CONSTRAINT PK_FAV_BOARD_LIKE PRIMARY KEY (MEMBER_ID_LIKE)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table GAME
--------------------------------------------------------

  ALTER TABLE GAME MODIFY (GAME_RANK NOT NULL ENABLE);
  ALTER TABLE GAME MODIFY (MEMBER_ID NOT NULL ENABLE);
  ALTER TABLE GAME MODIFY (GAME_SCORE NOT NULL ENABLE);
  ALTER TABLE GAME ADD CONSTRAINT PK_GAME PRIMARY KEY (GAME_RANK, MEMBER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE LOCATION MODIFY (MEMBER_ID NOT NULL ENABLE);
  ALTER TABLE LOCATION MODIFY (LOCATION_LATITUDE NOT NULL ENABLE);
  ALTER TABLE LOCATION MODIFY (LOCATION_LONGITUDE NOT NULL ENABLE);
  ALTER TABLE LOCATION ADD CONSTRAINT PK_LOCATION PRIMARY KEY (MEMBER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table MANNER
--------------------------------------------------------

  ALTER TABLE MANNER MODIFY (MANNER_OPPONENT_ID NOT NULL ENABLE);
  ALTER TABLE MANNER MODIFY (MEMBER_ID NOT NULL ENABLE);
  ALTER TABLE MANNER MODIFY (MANNER_SCORE NOT NULL ENABLE);
  ALTER TABLE MANNER ADD CONSTRAINT PK_MANNER PRIMARY KEY (MANNER_OPPONENT_ID, MEMBER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE MEMBER MODIFY (MEMBER_ID NOT NULL ENABLE);
  ALTER TABLE MEMBER MODIFY (MEMBER_PW NOT NULL ENABLE);
  ALTER TABLE MEMBER MODIFY (MEMBER_NAME NOT NULL ENABLE);
  ALTER TABLE MEMBER MODIFY (MEMBER_NICKNAME NOT NULL ENABLE);
  ALTER TABLE MEMBER MODIFY (MEMBER_AGE NOT NULL ENABLE);
  ALTER TABLE MEMBER MODIFY (MEMBER_GENDER NOT NULL ENABLE);
  ALTER TABLE MEMBER MODIFY (MEMBER_PHONE NOT NULL ENABLE);
  ALTER TABLE MEMBER MODIFY (MEMBER_MANNER_SCORE NOT NULL ENABLE);
  ALTER TABLE MEMBER MODIFY (MEMBER_ADMIN NOT NULL ENABLE);
  ALTER TABLE MEMBER ADD CHECK (member_gender in('남','여')) ENABLE;
  ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table OPTION_TABLE
--------------------------------------------------------

  ALTER TABLE OPTION_TABLE MODIFY (MEMBER_ID NOT NULL ENABLE);
  ALTER TABLE OPTION_TABLE MODIFY (OPTION_FONT_SIZE NOT NULL ENABLE);
  ALTER TABLE OPTION_TABLE MODIFY (OPTION_FONT_COLOR NOT NULL ENABLE);
  ALTER TABLE OPTION_TABLE MODIFY (OPTION_ALARM NOT NULL ENABLE);
  ALTER TABLE OPTION_TABLE MODIFY (OPTION_GODOK_ALARM NOT NULL ENABLE);
  ALTER TABLE OPTION_TABLE ADD CHECK (option_alarm in('Y','N')) ENABLE;
  ALTER TABLE OPTION_TABLE ADD CHECK (option_godok_alarm in('Y','N')) ENABLE;
  ALTER TABLE OPTION_TABLE ADD CONSTRAINT PK_OPTION_TABLE PRIMARY KEY (MEMBER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE REGION MODIFY (REGION NOT NULL ENABLE);
  ALTER TABLE REGION MODIFY (MEMBER_ID NOT NULL ENABLE);
  ALTER TABLE REGION ADD CONSTRAINT PK_REGION PRIMARY KEY (REGION, MEMBER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table SENIOR
--------------------------------------------------------

  ALTER TABLE SENIOR MODIFY (KEY NOT NULL ENABLE);
  ALTER TABLE SENIOR MODIFY (SENIOR_NAME NOT NULL ENABLE);
  ALTER TABLE SENIOR ADD CONSTRAINT PK_SENIOR PRIMARY KEY (KEY)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Constraints for Table SENIOR_LIKE
--------------------------------------------------------

  ALTER TABLE SENIOR_LIKE MODIFY (MEMBER_ID NOT NULL ENABLE);
  ALTER TABLE SENIOR_LIKE MODIFY (KEY NOT NULL ENABLE);
  ALTER TABLE SENIOR_LIKE MODIFY (SENIOR_LIKE_NUM NOT NULL ENABLE);
  ALTER TABLE SENIOR_LIKE ADD CONSTRAINT PK_SENIOR_LIKE PRIMARY KEY (MEMBER_ID, KEY)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CALL
--------------------------------------------------------

  ALTER TABLE CALL ADD CONSTRAINT FK_MEMBER_TO_CALL_1 FOREIGN KEY (MEMBER_ID)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMON2
--------------------------------------------------------

  ALTER TABLE COMMON2 ADD CONSTRAINT FK_COMMON1_TO_COMMON2_1 FOREIGN KEY (KEY1)
	  REFERENCES COMMON1 (KEY1) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CSBOARD
--------------------------------------------------------

  ALTER TABLE CSBOARD ADD CONSTRAINT FK_MEMBER_TO_CSBOARD_1 FOREIGN KEY (WRITER)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CSBOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE CSBOARD_COMMENT ADD CONSTRAINT FK_CSBOARD_TO_CSBOARD_COMMENT_1 FOREIGN KEY (CSBOARD_ID)
	  REFERENCES CSBOARD (CSBOARD_ID) ENABLE;
  ALTER TABLE CSBOARD_COMMENT ADD CONSTRAINT FK_MEMBER_TO_CSBOARD_COMMENT_1 FOREIGN KEY (WRITER)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DDAY
--------------------------------------------------------

  ALTER TABLE DDAY ADD CONSTRAINT FK_MEMBER_TO_DDAY_1 FOREIGN KEY (MEMBER_ID)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EPHONE
--------------------------------------------------------

  ALTER TABLE EPHONE ADD CONSTRAINT FK_MEMBER_TO_EPHONE_1 FOREIGN KEY (MEMBER_ID)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FAVOR
--------------------------------------------------------

  ALTER TABLE FAVOR ADD CONSTRAINT FK_MEMBER_TO_FAVOR_1 FOREIGN KEY (MEMBER_ID)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FAV_BOARD
--------------------------------------------------------

  ALTER TABLE FAV_BOARD ADD CONSTRAINT FK_MEMBER_TO_FAV_BOARD_1 FOREIGN KEY (WRITER)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FAV_BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE FAV_BOARD_COMMENT ADD CONSTRAINT FK_MEMBER_TO_FAV_BOARD_COMMENT_1 FOREIGN KEY (WRITER)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
  ALTER TABLE FAV_BOARD_COMMENT ADD CONSTRAINT FK_FAV_BOARD_TO_FAV_BOARD_COMMENT_1 FOREIGN KEY (FAV_BOARD_ID)
	  REFERENCES FAV_BOARD (FAV_BOARD_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FAV_BOARD_LIKE
--------------------------------------------------------

  ALTER TABLE FAV_BOARD_LIKE ADD CONSTRAINT FK_MEMBER_TO_FAV_BOARD_LIKE_1 FOREIGN KEY (MEMBER_ID_LIKE)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
  ALTER TABLE FAV_BOARD_LIKE ADD CONSTRAINT FK_FAV_BOARD_TO_FAV_BOARD_LIKE_1 FOREIGN KEY (FAV_BOARD_ID)
	  REFERENCES FAV_BOARD (FAV_BOARD_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GAME
--------------------------------------------------------

  ALTER TABLE GAME ADD CONSTRAINT FK_MEMBER_TO_GAME_1 FOREIGN KEY (MEMBER_ID)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE LOCATION ADD CONSTRAINT FK_MEMBER_TO_LOCATION_1 FOREIGN KEY (MEMBER_ID)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANNER
--------------------------------------------------------

  ALTER TABLE MANNER ADD CONSTRAINT FK_MEMBER_TO_MANNER_1 FOREIGN KEY (MEMBER_ID)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OPTION_TABLE
--------------------------------------------------------

  ALTER TABLE OPTION_TABLE ADD CONSTRAINT FK_MEMBER_TO_OPTION_TABLE_1 FOREIGN KEY (MEMBER_ID)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE REGION ADD CONSTRAINT FK_MEMBER_TO_REGION_1 FOREIGN KEY (MEMBER_ID)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SENIOR_LIKE
--------------------------------------------------------

  ALTER TABLE SENIOR_LIKE ADD CONSTRAINT FK_MEMBER_TO_SENIOR_LIKE_1 FOREIGN KEY (MEMBER_ID)
	  REFERENCES MEMBER (MEMBER_ID) ENABLE;
  ALTER TABLE SENIOR_LIKE ADD CONSTRAINT FK_SENIOR_TO_SENIOR_LIKE_1 FOREIGN KEY (KEY)
	  REFERENCES SENIOR (KEY) ENABLE;
