select * from friend_list;

delete friend_list where member_id = 'aa1aa' and friend_id = 'bb1bb';

rollback;
commit;
select * from member order by member_id;
select * from ephone;
select * from favor;

insert into member(MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
values('id004', '123qwe!@', '권은희', '삐삐', '65/01/31 00:00:00', '여', '01056257223', '경북 경주시 양정로 260 경주시청');

insert into EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
values('id004', '문병준', '01056257223', '아들', sysdate);

insert into FAVOR(FAVOR, MEMBER_ID)
values(1, 'id002');
insert into FAVOR(FAVOR, MEMBER_ID)
values(2, 'id002');
insert into FAVOR(FAVOR, MEMBER_ID)
values(3, 'id004');

INSERT ALL
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(1, 'user1')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(2, 'user1')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(4, 'user1')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(2, 'user2')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(9, 'user2')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(1, 'user3')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(4, 'user3')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(7, 'user4')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(8, 'user4')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(9, 'user4')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(1, 'user5')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(5, 'user5')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(6, 'user5')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(7, 'user6')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(1, 'user7')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(8, 'user8')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(9, 'user9')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(3, 'user10')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(5, 'user10')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(6, 'user10')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(1, 'user11')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(2, 'user12')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(3, 'user13')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(4, 'user14')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(5, 'user15')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(6, 'user16')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(7, 'user17')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(8, 'user18')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(9, 'user19')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(5, 'user20')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(1, 'user21')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(2, 'user22')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(3, 'user23')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(4, 'user24')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(5, 'user25')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(6, 'user26')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(7, 'user27')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(8, 'user28')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(9, 'user29')
INTO FAVOR(FAVOR, MEMBER_ID)
VALUES
(7, 'user30')
SELECT 1 FROM DUAL;


INSERT ALL
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user1', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user2', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user3', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user4', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user5', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user6', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user7', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user8', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user9', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user10', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user11', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user12', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user13', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user14', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user15', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user16', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user17', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user18', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user19', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user20', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user21', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user22', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user23', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user24', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user25', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user26', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user27', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user28', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user29', '문병준', '01056257223', '아들', sysdate)
INTO EPHONE(MEMBER_ID, EPHONE_NAME, EPHONE_PHONE, EPHONE_RELATION, EPHONE_TIME)
VALUES
('user30', '문병준', '01056257223', '아들', sysdate)
SELECT 1 FROM DUAL;



INSERT ALL
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user1', 'password1', '이길동', '길동이', TO_DATE('1962-03-21', 'yyyy-mm-dd'), '남', '0104567890', '서울시 강남구 강남대로 123')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user2', 'password2', '박길순', '길순이', TO_DATE('1959-08-15', 'yyyy-mm-dd'), '여', '0106543210', '서울시 서초구 반포대로 456')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user3', 'password3', '김영자', '영자언니', TO_DATE('1955-05-10', 'yyyy-mm-dd'), '여', '0101237890', '경북 경주시 양정로 260 경주시청')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user4', 'password4', '정기호', '기호형', TO_DATE('1960-11-25', 'yyyy-mm-dd'), '남', '0108885555', '전북 익산시 인북로 251-9 상가')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user5', 'password5', '이영숙', '영숙누나', TO_DATE('1954-12-20', 'yyyy-mm-dd'), '여', '0104442222', '경남 거창군 거창읍 상동2길 39')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user6', 'password6', '박진수', '진수오빠', TO_DATE('1967-06-30', 'yyyy-mm-dd'), '남', '0102223333', '전남 여수시 흥국로 99-1')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user7', 'password7', '김미영', '미영언니', TO_DATE('1960-02-18', 'yyyy-mm-dd'), '여', '0106667777', '전남 구례군 광의면 구만제로 128')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user8', 'password8', '이대희', '대희형', TO_DATE('1956-07-15', 'yyyy-mm-dd'), '남', '0109991111', '울산 중구 구교로 92 학성동주민센터')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user9', 'password9', '최미정', '미정누나', TO_DATE('1960-11-05', 'yyyy-mm-dd'), '여', '0102229999', '경북 영천시 동문길 30')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user10', 'password10', '김동수', '동수오빠', TO_DATE('1958-09-08', 'yyyy-mm-dd'), '남', '0104446666', '강원 양양군 군청길 39 양양초등학교')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user11', 'password11', '홍길동', '길동형', TO_DATE('1965-04-14', 'yyyy-mm-dd'), '남', '0105557777', '강원 인제군 인제읍 인제로112번길 36-13')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user12', 'password12', '이순신', '순신씨', TO_DATE('1968-08-08', 'yyyy-mm-dd'), '남', '0106668888', '경기 가평군 가평읍 연인2길 13-8 3층')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user13', 'password13', '신사임당', '임당씨', TO_DATE('1963-02-28', 'yyyy-mm-dd'), '여', '0107775555', '경기 의정부시 범골로145번길 25 1층')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user14', 'password14', '김유신', '유신형', TO_DATE('1969-12-05', 'yyyy-mm-dd'), '남', '0108882222', '인천 남동구 서창남순환로 9')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user15', 'password15', '윤봉길', '봉길이', TO_DATE('1964-05-12', 'yyyy-mm-dd'), '남', '0109997777', '경기 화성시 남양읍 역골중앙로41번길 14-9')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user16', 'password16', '김철수', '철수형', TO_DATE('1957-09-18', 'yyyy-mm-dd'), '남', '0108889999', '충남 당진시 송악읍 중흥2길 14-31')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user17', 'password17', '박미영', '미영누나', TO_DATE('1963-11-30', 'yyyy-mm-dd'), '여', '0105553337', '충남 부여군 부여읍 궁남로 23 부여군산림조합')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user18', 'password18', '이상민', '상민이', TO_DATE('1966-06-25', 'yyyy-mm-dd'), '남', '0109996666', '전북 전주시 완산구 홍산로 254')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user19', 'password19', '김영희', '영희씨', TO_DATE('1965-04-02', 'yyyy-mm-dd'), '여', '0107775555', '전북 고창군 아산면 중복길 32')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user20', 'password20', '정태호', '태호형', TO_DATE('1970-01-10', 'yyyy-mm-dd'), '남', '0105559999', '전남 영광군 군서면 군서로2길 64')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user21', 'password21', '이은지', '은지누나', TO_DATE('1972-07-12', 'yyyy-mm-dd'), '여', '0107773333', '전남 무안군 무안읍 무안로 440')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user22', 'password22', '박동민', '동민이', TO_DATE('1971-03-05', 'yyyy-mm-dd'), '남', '0109996666', '전남 진도군 진도읍 포산길 1 포산리사무소')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user23', 'password23', '김미영', '미영아', TO_DATE('1975-12-15', 'yyyy-mm-dd'), '여', '0105557777', '전남 해남군 북일면 용일길 53 용운리 마을회관')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user24', 'password24', '최영수', '영수형', TO_DATE('1973-09-28', 'yyyy-mm-dd'), '남', '0107771115', '경남 남해군 남해읍 화전로78번길 30 경남도립남해대학')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user25', 'password25', '이지은', '지은누나', TO_DATE('1974-04-30', 'yyyy-mm-dd'), '여', '0105552227', '경남 사천시 구암두문로 24 사천농협하나로마트')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user26', 'password26', '김민수', '민수형', TO_DATE('1978-03-14', 'yyyy-mm-dd'), '남', '0103335557', '경남 김해시 구지로 127')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user27', 'password27', '이수진', '수진언니', TO_DATE('1980-11-25', 'yyyy-mm-dd'), '여', '0105558888', '경북 경산시 압량읍 가일길 128')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user28', 'password28', '박준호', '준호형', TO_DATE('1982-09-08', 'yyyy-mm-dd'), '남', '0109994448', '서울시 강북구 강북로 123')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user29', 'password29', '김예린', '예린누나', TO_DATE('1981-05-17', 'yyyy-mm-dd'), '여', '0107773339', '서울시 도봉구 도봉로 456')
INTO MEMBER (MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_NICKNAME, MEMBER_BIRTH, MEMBER_GENDER, MEMBER_PHONE, MEMBER_ADDRESS)
VALUES
('user30', 'password30', '정승우', '승우형', TO_DATE('1977-12-30', 'yyyy-mm-dd'), '남', '0105552224', '서울시 종로구 종로 789')
SELECT 1 FROM DUAL;
